name: update-vestaboard

on:
  # Schedule the workflow to run every 10 minutes
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update-vestaboard:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run orchestration script
        id: supercluster
        run: |
          python main.py
        env:
          AIDY_API_URL: ${{ secrets.AIDY_API_URL }}
          TWITTER_USERS: ${{ secrets.TWITTER_USERS }}
          SANITY_API_URL: ${{ secrets.SANITY_API_URL }}
          VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }}
          TWITTER_AUTH_TOKEN: ${{ secrets.TWITTER_AUTH_TOKEN }}

      - name: Persist Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update persistent data
