name: update-vestaboard

on:
  schedule:
    - cron: '0,20,40 12-21 * * *' # Every 20 minutes from 8 am to 6 pm EDT
  push:
    branches:
      - main

jobs:
  update-vestaboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run supercluster script
        id: supercluster
        run: |
          python supercluster.py | tee output.log
        env:
          SANITY_API_URL: ${{ secrets.SANITY_API_URL }}
          VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }}

      - name: Initialize result.txt if it does not exist
        run: |
          if [ ! -f result.txt ]; then
            echo "false" > result.txt
          fi

      - name: Check if Supercluster message has changed
        run: |
          if grep -q 'The message is the same as the last one. No update needed.' output.log; then
            echo "true" > result.txt
          else
            echo "false" > result.txt
          fi

      - name: Set environment variable
        run: echo "same_message=$(cat result.txt)" >> $GITHUB_ENV

      - name: Debug same_message
        run: echo "same_message=$same_message"

      - name: Run spacenews script if Supercluster message is unchanged
        if: env.same_message == 'true'
        run: python spacenews.py
        env:
          SANITY_API_URL: ${{ secrets.SANITY_API_URL }}
          VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }}

      - name: Send message to Vestaboard
        if: env.same_message == 'true'
        run: |
          url='https://rw.vestaboard.com/'
          headers={
            'X-Vestaboard-Read-Write-Key': VESTABOARD_API_KEY,
            'Content-Type': 'application/json'
          }
          data=json.dumps(message_layout)
          response=requests.post(url, headers=headers, data=data)
          if response.status_code == 200:
            print("Message sent to Vestaboard successfully!")
          else:
            print("Failed to send message to Vestaboard")
            print("Response:", response.text)
