name: update-vestaboard

on:
  # Allows manual trigger of the workflow from the Actions tab
  workflow_dispatch:

  # Run the workflow when code is pushed to a specific branch
  push:
    branches:
      - feat-integrations-re # Replace with the name of the branch you want, e.g., 'develop'

jobs:
  update-vestaboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run supercluster script
        id: supercluster
        run: |
          python main.py
        env:
          AIDY_API_URL: ${{ secrets.AIDY_API_URL }}
          TWITTER_USERS: ${{ secrets.TWITTER_USERS }}
          SANITY_API_URL: ${{ secrets.SANITY_API_URL }}
          VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }}
          TWITTER_AUTH_TOKEN: ${{ secrets.TWITTER_AUTH_TOKEN }}

      - name: Persist Data
        run: |
          git add ./data.json
          git commit -m "Updated Persistent data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}