name: update-vestaboard

on:
  # Allows manual trigger of the workflow from the Actions tab
  workflow_dispatch:

  # Run the workflow when code is pushed to a specific branch
  push:
    branches:
      - feat-integrations-re # Replace with the name of the branch you want, e.g., 'develop'

jobs:
  update-vestaboard:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run orchestration script
        id: supercluster
        run: |
          python main.py
        env:
          AIDY_API_URL: ${{ secrets.AIDY_API_URL }}
          TWITTER_USERS: ${{ secrets.TWITTER_USERS }}
          SANITY_API_URL: ${{ secrets.SANITY_API_URL }}
          VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }}
          TWITTER_AUTH_TOKEN: ${{ secrets.TWITTER_AUTH_TOKEN }}

      - name: Persist Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update persistent data